<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="EduSync connects school administration, teachers, and students—even when connectivity is limited."><title>EduSync — Learning that stays connected</title>@vite(['resources/css/app.css'])</head>
<body class="bg-white text-slate-900">
<header class="fixed inset-x-0 top-0 z-50 border-b border-slate-200/70 bg-white/90 backdrop-blur-xl"><nav class="mx-auto flex h-18 max-w-7xl items-center justify-between px-5 py-4 lg:px-8" aria-label="Main navigation"><a href="/" class="flex items-center gap-2.5"><span class="grid h-9 w-9 place-items-center rounded-xl bg-blue-700 font-black text-white">E</span><span class="text-lg font-bold tracking-tight">EduSync</span></a><div class="hidden items-center gap-8 text-sm font-medium text-slate-600 md:flex"><a class="hover:text-blue-700" href="#features">Features</a><a class="hover:text-blue-700" href="#how-it-works">How it works</a><a class="hover:text-blue-700" href="#about">About</a></div><a href="{{ route('login') }}" class="rounded-xl bg-slate-900 px-5 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:-translate-y-0.5 hover:bg-blue-700">Log in to EduSync</a></nav></header>
<main>
 <section class="relative overflow-hidden bg-slate-950 pt-32 text-white"><div class="absolute inset-0 opacity-30" style="background-image:radial-gradient(circle at 70% 20%,#2563eb 0,transparent 32%),radial-gradient(circle at 20% 80%,#0f766e 0,transparent 28%)"></div><div class="relative mx-auto grid max-w-7xl items-center gap-14 px-5 pb-20 pt-12 lg:grid-cols-2 lg:px-8 lg:pb-28"><div><span class="inline-flex rounded-full border border-blue-400/30 bg-blue-400/10 px-3 py-1 text-xs font-semibold uppercase tracking-widest text-blue-200">Built for connected classrooms</span><h1 class="mt-6 text-4xl font-black leading-tight tracking-tight sm:text-6xl">One school.<br><span class="text-blue-400">Always in sync.</span></h1><p class="mt-6 max-w-xl text-lg leading-8 text-slate-300">Bring classes, assessments, learning materials, grades, and school operations together—online or offline.</p><div class="mt-8 flex flex-col gap-3 sm:flex-row"><a href="{{ route('login') }}" class="rounded-xl bg-blue-600 px-6 py-3.5 text-center font-semibold text-white shadow-lg shadow-blue-900/30 hover:bg-blue-500">Access your portal →</a><a href="#how-it-works" class="rounded-xl border border-white/20 bg-white/5 px-6 py-3.5 text-center font-semibold hover:bg-white/10">See how it works</a></div><div class="mt-9 flex flex-wrap gap-x-6 gap-y-2 text-sm text-slate-400"><span>✓ Role-based access</span><span>✓ Offline-ready learning</span><span>✓ Secure school data</span></div></div>
 <div class="relative"><div class="absolute -inset-6 rounded-[2rem] bg-blue-500/20 blur-3xl"></div><div class="relative rounded-3xl border border-white/15 bg-white/10 p-4 shadow-2xl backdrop-blur"><div class="rounded-2xl bg-white p-5 text-slate-900"><div class="flex items-center justify-between border-b pb-4"><div><p class="text-xs font-semibold uppercase tracking-wider text-blue-600">Teacher workspace</p><p class="font-bold">Good morning, Teacher</p></div><span class="h-9 w-9 rounded-full bg-blue-100"></span></div><div class="mt-4 grid grid-cols-3 gap-3">@foreach([['Students','128'],['Classes','6'],['To grade','14']] as $stat)<div class="rounded-xl bg-slate-50 p-3"><p class="text-xl font-bold">{{ $stat[1] }}</p><p class="text-xs text-slate-500">{{ $stat[0] }}</p></div>@endforeach</div><div class="mt-4 rounded-xl border p-4"><div class="mb-3 flex justify-between"><p class="text-sm font-semibold">Today’s classes</p><span class="text-xs text-blue-600">View all</span></div>@foreach(['Science · Grade 8','Mathematics · Grade 9','English · Grade 7'] as $class)<div class="mb-2 flex items-center gap-3 rounded-lg bg-slate-50 p-2.5 last:mb-0"><span class="h-2 w-2 rounded-full bg-blue-500"></span><span class="text-sm font-medium">{{ $class }}</span></div>@endforeach</div></div></div></div></div>
 </section>
 <section id="features" class="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div class="mx-auto max-w-2xl text-center"><p class="text-sm font-bold uppercase tracking-widest text-blue-700">Everything your school needs</p><h2 class="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">Designed around how schools actually work</h2><p class="mt-4 text-slate-600">Purpose-built tools for every member of your learning community.</p></div><div class="mt-14 grid gap-5 md:grid-cols-3">@foreach([['Teach with clarity','Manage classes, quizzes, assignments, submissions, grades, materials, reports, and learning analytics from one workspace.','bg-emerald-50 text-emerald-700'],['Learn without limits','Students can keep learning and completing work even with unreliable internet connectivity.','bg-blue-50 text-blue-700'],['Run school confidently','Manage people, subjects, classes, academic years, reports, security logs, sync health, and settings.','bg-violet-50 text-violet-700']] as $feature)<article class="rounded-2xl border border-slate-200 p-7 shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><span class="inline-flex rounded-xl px-3 py-2 text-sm font-bold {{ $feature[2] }}">0{{ $loop->iteration }}</span><h3 class="mt-6 text-xl font-bold">{{ $feature[0] }}</h3><p class="mt-3 leading-7 text-slate-600">{{ $feature[1] }}</p></article>@endforeach</div></section>
 <section id="how-it-works" class="bg-slate-50 py-24"><div class="mx-auto max-w-7xl px-5 lg:px-8"><div class="grid gap-14 lg:grid-cols-2 lg:items-center"><div><p class="text-sm font-bold uppercase tracking-widest text-blue-700">Simple by design</p><h2 class="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">From classroom to home, in three steps.</h2><p class="mt-4 text-slate-600">EduSync keeps the workflow familiar while handling connectivity in the background.</p></div><ol class="space-y-5">@foreach([['Teachers prepare','Create classes, publish activities, and share learning resources.'],['Students keep learning','Access lessons and complete schoolwork online or offline.'],['EduSync brings it together','Changes synchronize safely when a connection becomes available.']] as $step)<li class="flex gap-5 rounded-2xl bg-white p-5 shadow-sm"><span class="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-blue-700 font-bold text-white">{{ $loop->iteration }}</span><div><h3 class="font-bold">{{ $step[0] }}</h3><p class="mt-1 text-sm leading-6 text-slate-600">{{ $step[1] }}</p></div></li>@endforeach</ol></div></div></section>
 <section id="about" class="mx-auto max-w-5xl px-5 py-24 text-center"><h2 class="text-3xl font-bold tracking-tight">Ready for a more connected school day?</h2><p class="mx-auto mt-4 max-w-xl text-slate-600">Sign in to your secure EduSync workspace and pick up exactly where you left off.</p><a href="{{ route('login') }}" class="mt-8 inline-flex rounded-xl bg-blue-700 px-7 py-3.5 font-semibold text-white shadow-lg shadow-blue-200 hover:bg-blue-800">Log in to your portal</a></section>
</main>
<footer class="border-t border-slate-800 bg-slate-950 text-slate-400"><div class="mx-auto flex max-w-7xl flex-col gap-6 px-5 py-10 sm:flex-row sm:items-center sm:justify-between lg:px-8"><div><div class="flex items-center gap-2 text-white"><span class="grid h-8 w-8 place-items-center rounded-lg bg-blue-600 font-black">E</span><span class="font-bold">EduSync</span></div><p class="mt-2 text-sm">Learning that stays connected.</p></div><div class="flex gap-6 text-sm"><a class="hover:text-white" href="#features">Features</a><a class="hover:text-white" href="#how-it-works">How it works</a><a class="hover:text-white" href="{{ route('login') }}">Login</a></div><p class="text-xs">© {{ date('Y') }} EduSync. All rights reserved.</p></div></footer>
</body></html>
