import { Head, Link } from '@inertiajs/react';
import TeacherLayout from '@/Layouts/TeacherLayout';
import { EmptyState, SectionCard, StatCard, StatusBadge, TableShell } from '@/Components/PortalUI';
import { formatDateTime } from '@/utils/teacher';

export default function Dashboard({ stats = {}, classes = [], upcoming_deadlines = [], recent_activity = [] }) {
 return <TeacherLayout title="Teaching overview"><Head title="Teacher Dashboard" />
  <div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-emerald-700">Your classroom at a glance</p><h2 className="mt-1 text-2xl font-bold tracking-tight text-slate-900">Make today count.</h2><p className="mt-1 text-sm text-slate-500">Live information from your classes, assessments, and gradebook.</p></div><div className="flex gap-2"><Link href="/teacher/assignments/create" className="portal-btn-secondary">New assignment</Link><Link href="/teacher/quizzes/create" className="portal-btn-primary">Create quiz</Link></div></div>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Enrolled students" value={stats.students} helper="Across all your classes" icon="users" tone="green" href="/teacher/classes"/><StatCard label="Published quizzes" value={stats.active_quizzes} helper="Currently available" icon="quiz" tone="violet" href="/teacher/quizzes"/><StatCard label="Active assignments" value={stats.active_assignments} helper="Open for submissions" icon="assignment" tone="blue" href="/teacher/assignments"/><StatCard label="Needs grading" value={stats.pending_grading} helper="Submissions awaiting review" icon="file" tone="amber" href="/teacher/submissions"/></div>
  <div className="mt-6 grid gap-6 xl:grid-cols-5"><SectionCard title="My classes" subtitle={`${classes.length} classes assigned to you`} className="xl:col-span-3" action={<Link href="/teacher/classes" className="text-sm font-semibold text-emerald-700">View all</Link>}>
   {classes.length ? <div className="grid gap-3 sm:grid-cols-2">{classes.slice(0,4).map(c=><Link key={c.id} href={`/teacher/classes/${c.id}`} className="rounded-xl border border-slate-200 p-4 transition hover:-translate-y-0.5 hover:border-emerald-300 hover:shadow-sm"><div className="flex items-start justify-between gap-2"><div><h3 className="font-semibold text-slate-900">{c.name}</h3><p className="text-sm text-slate-500">{c.section} · {c.subject?.name || 'No subject'}</p></div><span className="rounded-lg bg-emerald-50 px-2 py-1 text-xs font-bold text-emerald-700">{c.students_count}</span></div></Link>)}</div>:<EmptyState title="No classes assigned" description="Classes assigned to you will appear here."/>}
  </SectionCard><SectionCard title="Upcoming deadlines" subtitle="Next items due" className="xl:col-span-2">{upcoming_deadlines.length?<div className="space-y-3">{upcoming_deadlines.map((item,i)=><div key={`${item.id}-${i}`} className="flex gap-3 rounded-xl bg-slate-50 p-3"><span className="mt-1 h-2 w-2 shrink-0 rounded-full bg-amber-400"/><div><p className="text-sm font-semibold text-slate-800">{item.title}</p><p className="mt-0.5 text-xs text-slate-500">{formatDateTime(item.deadline)}</p></div></div>)}</div>:<EmptyState title="You’re all caught up" description="No upcoming quiz or assignment deadlines."/>}</SectionCard></div>
  <SectionCard title="Recent submissions" subtitle="Latest quiz activity from your students" className="mt-6" action={<Link href="/teacher/submissions" className="text-sm font-semibold text-emerald-700">Open submissions</Link>}>{recent_activity.length?<TableShell><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3 text-left">Student</th><th className="px-4 py-3 text-left">Assessment</th><th className="px-4 py-3 text-left">Score</th><th className="px-4 py-3 text-left">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{recent_activity.map(a=><tr key={a.id} className="hover:bg-slate-50"><td className="px-4 py-3 font-medium text-slate-800">{a.student?.first_name} {a.student?.last_name}</td><td className="px-4 py-3 text-slate-600">{a.quiz?.title}</td><td className="px-4 py-3 text-slate-600">{a.score ?? '—'} / {a.total_points ?? '—'}</td><td className="px-4 py-3"><StatusBadge tone={(a.status?.value||a.status)==='graded'?'green':'amber'}>{a.status?.value||a.status}</StatusBadge></td></tr>)}</tbody></TableShell>:<EmptyState title="No recent submissions" description="Student quiz attempts will appear here."/>}</SectionCard>
 </TeacherLayout>;
}
