<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><meta name="theme-color" content="#0f172a"><title>Sign in — {{ config('app.name', 'EduSync') }}</title>@vite(['resources/css/app.css', 'resources/js/app.js'])</head>
<body class="antialiased">
<main class="grid min-h-screen bg-white lg:grid-cols-2">
 <section class="relative hidden overflow-hidden bg-slate-950 p-12 text-white lg:flex lg:flex-col lg:justify-between"><div class="absolute inset-0 opacity-40" style="background:radial-gradient(circle at 15% 15%,#2563eb 0,transparent 28rem),radial-gradient(circle at 85% 85%,#059669 0,transparent 25rem)"></div><a href="/" class="relative flex items-center gap-3"><span class="grid h-11 w-11 place-items-center rounded-xl bg-white text-xl font-black text-slate-950">E</span><div><p class="text-xl font-bold">EduSync</p><p class="text-xs text-slate-400">Connected school platform</p></div></a><div class="relative max-w-xl"><span class="inline-flex rounded-full border border-white/15 bg-white/10 px-3 py-1 text-xs font-semibold uppercase tracking-widest text-blue-200">Learn · Teach · Manage</span><h2 class="mt-6 text-5xl font-black leading-tight tracking-tight">Your school day,<br><span class="text-blue-400">beautifully organized.</span></h2><p class="mt-5 max-w-lg text-lg leading-8 text-slate-300">One secure workspace for lessons, assessments, grades, reports, and school operations—built to keep working when connectivity does not.</p><div class="mt-9 grid grid-cols-3 gap-3">@foreach([['Teacher','Classes & grading'],['Admin','School operations'],['Student','Offline learning']] as $item)<div class="rounded-2xl border border-white/10 bg-white/5 p-4 backdrop-blur"><p class="font-bold">{{ $item[0] }}</p><p class="mt-1 text-xs text-slate-400">{{ $item[1] }}</p></div>@endforeach</div></div><p class="relative text-xs text-slate-500">© {{ date('Y') }} EduSync · Secure role-based access</p></section>
 <section class="flex min-h-screen flex-col bg-slate-50 lg:bg-white"><div class="flex items-center justify-between px-5 py-5 lg:hidden"><a href="/" class="flex items-center gap-2"><span class="grid h-9 w-9 place-items-center rounded-xl bg-slate-950 font-black text-white">E</span><span class="font-bold">EduSync</span></a><a href="/" class="text-sm font-semibold text-slate-500">Back home</a></div><div class="flex flex-1 items-center justify-center px-5 py-10 sm:px-8"><div class="w-full max-w-md rounded-3xl border border-slate-200 bg-white p-6 shadow-xl shadow-slate-200/60 sm:p-9 lg:border-0 lg:p-0 lg:shadow-none">{{ $slot }}</div></div></section>
</main>
</body></html>
