import { Head, Link } from '@inertiajs/react';
import AdminLayout from '@/Layouts/AdminLayout';
import { EmptyState, SectionCard, StatCard, StatusBadge } from '@/Components/PortalUI';
import { formatDateTime } from '@/utils/admin';

export default function Dashboard({ stats={}, system_usage={}, recent_activities=[], recent_sync=[], enrollment_chart={labels:[],values:[]}, completion_chart={labels:[],values:[]} }) {
 const max=Math.max(...(enrollment_chart.values||[]),1); const syncTone=s=>['completed','success','synced'].includes(String(s).toLowerCase())?'green':String(s).toLowerCase()==='failed'?'red':'amber';
 return <AdminLayout title="School overview"><Head title="Admin Dashboard" />
  <div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-blue-700">Operations center</p><h2 className="mt-1 text-2xl font-bold tracking-tight text-slate-900">Everything in one place.</h2><p className="mt-1 text-sm text-slate-500">Live school data from MySQL, updated with every request.</p></div><Link href="/admin/users/create" className="portal-btn-primary">Add user</Link></div>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Students" value={stats.students} icon="users" tone="blue" href="/admin/users?role=student"/><StatCard label="Teachers" value={stats.teachers} icon="users" tone="green" href="/admin/users?role=teacher"/><StatCard label="Classes" value={stats.classes} icon="class" tone="violet" href="/admin/classes"/><StatCard label="Active users" value={stats.active_users} icon="shield" tone="cyan" href="/admin/users?status=active"/></div>
  <div className="mt-6 grid gap-6 xl:grid-cols-5"><SectionCard title="Enrollment trend" subtitle="New student accounts by month" className="xl:col-span-3"><div className="flex h-52 items-end gap-3 border-b border-slate-200 px-1 pt-5">{enrollment_chart.labels.map((label,i)=><div key={label} className="group flex h-full flex-1 flex-col justify-end text-center"><span className="mb-1 text-xs font-semibold text-slate-600 opacity-0 transition group-hover:opacity-100">{enrollment_chart.values[i]}</span><div className="min-h-1 rounded-t-lg bg-blue-600 transition hover:bg-blue-700" style={{height:`${Math.max((enrollment_chart.values[i]/max)*80,2)}%`}}/><span className="mt-2 truncate text-[10px] text-slate-500 sm:text-xs">{label}</span></div>)}</div></SectionCard><SectionCard title="Completion health" subtitle="Assessment completion rates" className="xl:col-span-2"><div className="space-y-6 py-2">{completion_chart.labels.map((label,i)=><div key={label}><div className="mb-2 flex justify-between text-sm"><span className="font-medium text-slate-700">{label}</span><span className="font-bold text-slate-900">{completion_chart.values[i]}%</span></div><div className="h-2.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-blue-600 to-cyan-400" style={{width:`${Math.min(completion_chart.values[i],100)}%`}}/></div></div>)}</div></SectionCard></div>
  <div className="mt-6 grid gap-6 xl:grid-cols-2"><SectionCard title="Recent school activity" subtitle="Latest auditable changes" action={<Link href="/admin/audit-logs" className="text-sm font-semibold text-blue-700">Audit logs</Link>}>{recent_activities.length?<div className="space-y-1">{recent_activities.slice(0,6).map(log=><div key={log.id} className="flex gap-3 rounded-xl p-3 hover:bg-slate-50"><span className="mt-1.5 h-2 w-2 shrink-0 rounded-full bg-blue-500"/><div className="min-w-0"><p className="truncate text-sm font-medium text-slate-800">{log.description}</p><p className="mt-0.5 text-xs text-slate-400">{log.user?.full_name||'System'} · {formatDateTime(log.created_at)}</p></div></div>)}</div>:<EmptyState title="No activity recorded"/>}</SectionCard><SectionCard title="Synchronization monitoring" subtitle="Latest device and server sync events" action={<Link href="/admin/sync" className="text-sm font-semibold text-blue-700">Open monitor</Link>}>{recent_sync.length?<div className="space-y-1">{recent_sync.slice(0,6).map(log=><div key={log.id} className="flex items-center justify-between gap-3 rounded-xl p-3 hover:bg-slate-50"><div className="min-w-0"><p className="truncate text-sm font-medium text-slate-800">{log.message||'Synchronization event'}</p><p className="mt-0.5 text-xs text-slate-400">{log.user?.full_name||'System'} · {formatDateTime(log.created_at)}</p></div><StatusBadge tone={syncTone(log.status?.value||log.status)}>{log.status?.value||log.status||'logged'}</StatusBadge></div>)}</div>:<EmptyState title="No sync events" description="Synchronization activity will appear here."/>}</SectionCard></div>
  <SectionCard title="Platform inventory" subtitle="Current records in the school database" className="mt-6"><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{Object.entries({...system_usage,subjects:stats.subjects,quizzes:stats.quizzes,assignments:stats.assignments,submissions:stats.submissions}).map(([k,v])=><div key={k} className="rounded-xl bg-slate-50 p-3 text-center"><p className="text-xl font-bold text-slate-900">{v??0}</p><p className="mt-1 text-xs capitalize text-slate-500">{k.replaceAll('_',' ')}</p></div>)}</div></SectionCard>
 </AdminLayout>;
}
